{% set name = "badger-opt" %}
{% set version = "1.2.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 199c47cd471ee661a84f35333cc25f5b89528e969e24dbfd2be5092164a95167

build:
  number: 0
  noarch: python
  entry_points:
    - badger = badger.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools
  run:
    - python >=3.9
    - pyqt
    - pyqtgraph
    - qdarkstyle
    - coolname
    - pillow
    - requests
    - xopt

test:
  imports:
    - badger
  commands:
    - badger
  requires:
    - pip

about:
  home: https://github.com/slaclab/Badger
  summary: Badger optimizer
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - wenatuhs
    - pluflou
